### ISSUE TITLE
Error: Not supported on windows

### ISSUE THREAD

**Issue by aviadhahami** [danawoodman/react-fontawesome#13]
Hi, 
I'm getting this when trying to install your module:
![image](https://cloud.githubusercontent.com/assets/7353632/15084118/17233038-13da-11e6-98f9-ad5a30b57977.png)

Any suggestions?

**Comment by danawoodman** [comment]
Thanks for the report @aviadhahami. It seems that `babel` requires `fsevents` as a dependency and since the app runs a build step on `prepublish` (which is run when calling `npm install`), it calls this code.

I went ahead and removed the `prepublish` step so it should now work on windows. Download the latest version, `v1.1.0` and report back if it works or not 😄
