### ISSUE TITLE
Unable to view rendered icon

### ISSUE THREAD

**Issue by fergatron** [danawoodman/react-fontawesome#60]
Hi,
I installed react-fontawesome via npm and imported it into my React app. When I run the app I see the HTML render, but there's no ICON. Looking at web developer tools in Chrome I also don't see any CSS assignments nor a font-awesome css call in the network tab.

```
import FontAwesome from 'react-fontawesome';

<FontAwesome name='facebook' />
```

**Comment by prymorsk** [comment]
In your public folder add this line to your index.html file: 
    `<link href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' rel='stylesheet' integrity='sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN' crossorigin='anonymous'>`

**Comment by ivanberry** [comment]
Problem still:
 - install react-fontawesome
 - include font-awesome css with CDN or with npm and import
 - In Google DevTools, the font-awesome.css show
 - still fail to see the icons
![image](https://user-images.githubusercontent.com/13112910/34066449-bc46f9ac-e249-11e7-9792-1785390f6cc7.png)

**Comment by danawoodman** [comment]
@ivanberry can you try to see if FontAwesome works without react-fontawesome? Just try `<span className="fa fa-rocket" />` and see if the icon renders? If it doesn't, your issue is with the CSS not loading for some reason. Also check inspector to see if the font file is being loaded.

Gonna close but re-open if after those steps you still think it is react-fontawesome 👍

**Comment by fergatron** [comment]
Sorry I never got back to you. As stated the solution was for me to include the CSS file. For some reason I figured it would have been part of the package. I'm still wrapping my head around NPM.
