### ISSUE TITLE
How to specify the color of the icon? Looks like it's impossible...

### ISSUE THREAD

**Issue by Muzietto** [danawoodman/react-fontawesome#81]
I have been trying to change the drawing color of an icon, without success, e.g.

      <FontAwesomeIcon
        color='red'
        icon={faIcon}
        size='1x'
      />

Now I see at https://github.com/danawoodman/react-fontawesome/blob/HEAD/api.md that the component API does not seem to include "color", so I try:

      <FontAwesomeIcon
        style={{color: 'red'}}
        icon={faIcon}
        size='1x'
      />

Still it does not work. Is there a way to specify the icon color?

**Comment by danawoodman** [comment]
That is strange, there is no reason `style` should not work since we pass down all props to the component. Have you looked at the component in the inspector to make sure it is not being overridden elsewhere?

And yes, we do no provide a `color` prop. 

PS, If you're using this with FontAwesome 5,  you should use their official React component

**Comment by danawoodman** [comment]
Please reopen if you believe this is an issue
